---
driver:
  name: vagrant
  require_chef_omnibus: 12.3.0

provisioner:
  name: chef_zero
  data_path: 'test/shared'

platforms:
  - name: centos-6.6
    driver:
      provider: parallels
      box: parallels/centos-6.6
      require_chef_omnibus: 12.3.0

suites:
  - name: default
    data_bags_path: 'test/integration/data_bags'
    run_list:
      - recipe[hello_world::default]
    attributes: {}
