name             'hello_world'
maintainer       'SpinDance, Inc.'
maintainer_email 'davidr@spindance.com'
license          'All rights reserved'
description      'Installs/Configures hello_world'
long_description 'Installs/Configures hello_world'
version          '0.1.0'
depends 'nginx'
depends 'application', '~> 5.0.0'
depends 'application_git', '~> 1.1.0'
depends 'ssh_known_hosts'
